org: lucaslimao
app: musii

service: musii-sqs-services

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 512
    timeout: 10
    iamRoleStatements:
        - Effect: "Allow"
          Action:
          - sqs:SendMessage
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          - sqs:GetQueueAttributes
          Resource: "arn:aws:sqs:us-east-1:412490949371:FOLLOW"
        - Effect: "Allow"
          Action: 
          - logs:CreateLogGroup,
          - logs:PutRetentionPolicy
          - logs:CreateLogStream,
          - logs:PutLogEvents,
          - logs:DescribeLogStreams
          Resource: "arn:aws:logs:us-east-1:412490949371:log-group:/aws/rds/*"
        - Effect: "Allow"
          Action: 
            - logs:CreateLogStream,
            - logs:PutLogEvents,
            - logs:DescribeLogStreams,
            - logs:GetLogEvents
          Resource: "arn:aws:logs:us-east-1:412490949371:log-group:/aws/rds/*:log-stream:*"

functions:
    followConsumerHandler:
        handler: src/handlers/handler.consumer